{
 "title": "Cluster controller 2",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "successful runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_run_total{status=\"success\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "failed runs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "test_run_total{status=\"failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "test errors count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "test_run_errors_total{job=\"loadtest-agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "cluster-controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Actions executed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (type, success) (rate(action_executed_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control plane requests",
   "type": "timeseries",
   "description": "Shows total QPS by the client across all methods and plots it against the default QPS. Due to token bucket algorithm, line can go temporarily above the threshold but staying there will cause client throttling. ",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"cluster-controller\"}[1m])) by (method, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"cluster-controller\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cc errors rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "direction": "backward",
     "expr": "rate({namespace=\"castai-agent\", container=\"cluster-controller\", level=\"error\"}[1m])"
    }
   ]
  },
  {
   "title": "actions total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "sum by (type, success) (increase(action_executed_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Informer cache size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "informer_cache_size{resource=\"node\", job=\"cluster-controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC cycles count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(go_gc_duration_seconds_count{job=\"cluster-controller\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC pause duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"cluster-controller\"}[1m]) / rate(go_gc_duration_seconds_count{job=\"cluster-controller\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap MB allocated",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"cluster-controller\"} / (1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"cluster-controller\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of memory allocated (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"cluster-controller\"}[$__rate_interval]) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "ready nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{status=\"true\", condition=\"Ready\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "unsschedulable"
    }
   ]
  },
  {
   "title": "pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})",
     "legendFormat": "pending"
    }
   ]
  },
  { "title": "apiserver requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Client rate limit latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_rate_limiter_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(rest_client_rate_limiter_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(rest_client_rate_limiter_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "apiserver calls total",
   "type": "timeseries",
   "description": "Shows total QPS by the client across all methods and plots it against the default QPS. Due to token bucket algorithm, line can go temporarily above the threshold but staying there will cause client throttling. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total[1m]))",
     "legendFormat": "Total QPS"
    }
   ]
  },
  {
   "title": "server-side throttle responses (429)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{code=\"429\"}[1m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "apiserver latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(rest_client_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(rest_client_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "apiserver calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total[1m])) by (method, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } }
 ]
}