version: "2"
linters:
  default: none
  enable:
    - containedctx
    - dogsled
    - dupword
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocognit
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - intrange
    - lll
    - misspell
    - modernize
    - nakedret
    - nilerr
    - predeclared
    - revive
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
  settings:
    goconst:
      min-len: 2
      min-occurrences: 5
    gocritic:
      disabled-checks:
        - commentFormatting
    godot:
      scope: all
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 200
    misspell:
      locale: US
    revive:
      rules:
        - name: redefines-builtin-id
          disabled: true
        - name: nested-structs
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - mock
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/castai/cluster-controller)
    gofumpt:
      module-path: github.com/castai/cluster-controller
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - mock
      - third_party$
      - builtin$
      - examples$
