apiVersion: v1
kind: ServiceAccount
metadata:
  name: castai-loadtest-agent-sa
  namespace: castai-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: castai-agent-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: castai-loadtest-agent-sa
    namespace: castai-agent
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: castai-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-role-binding
subjects:
  - kind: ServiceAccount
    name: prometheus-sa
    namespace: castai-agent
roleRef:
  kind: ClusterRole
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - /metrics
    verbs: ["get"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: castai-agent
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'cluster-controller'
        kubernetes_sd_configs:
        - role: pod
          namespaces:
            names:
              - castai-agent
        relabel_configs:
          # Filter targets based on a deployment label.
          - source_labels: [ __meta_kubernetes_pod_label_app_kubernetes_io_name ]
            action: keep
            regex: castai-cluster-controller
          # Explicitly set the scrape port to 9090 as this is what CC uses.
          - source_labels: [ __address__ ]
            regex: ([^:]+)(?::\d+)?
            target_label: __address__
            replacement: $1:9090
      - job_name: 'kubernetes-apiservers'
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https
      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
        - role: service
          namespaces:
            names:
              - castai-agent
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
            action: keep
            regex: kube-state-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: observability-service
  namespace: castai-agent
spec:
  selector:
    app: simple-observability
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: grafana
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-observability
  namespace: castai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-observability
  template:
    metadata:
      labels:
        app: simple-observability
    spec:
      serviceAccountName: prometheus-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - kwok
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
          volumeMounts:
            # Mount the datasource provisioning
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
              subPath: datasource.yaml
            # Mount the custom grafana.ini to disable login and enable anonymous access
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            # Mount the dashboards provisioning file
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
              subPath: dashboards.yaml
            # Mount the pre-created dashboards JSON file
            - name: grafana-config
              mountPath: /var/lib/grafana/dashboards/cluster-controller-dashboard.json
              subPath: cluster-controller-dashboard.json
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: grafana-config
          configMap:
            name: grafana-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-loadtest-agent
  namespace: castai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: castai-loadtest-agent
  template:
    metadata:
      labels:
        app: castai-loadtest-agent
    spec:
      serviceAccountName: castai-loadtest-agent-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - kwok
      containers:
        - name: castai-agent
          image: ${LOADTEST_REPOSITORY}:${LOADTEST_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command:
            - "castai-cluster-controller"
            - "test-server"
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: castai-loadtest-agent-service
  namespace: castai-agent
spec:
  selector:
    app: castai-loadtest-agent
  ports:
    - name: loadtest
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-state-metrics
  namespace: castai-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-state-metrics
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - nodes
      - pods
      - services
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - persistentvolumeclaims
      - persistentvolumes
      - namespaces
      - endpoints
    verbs: ["list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - daemonsets
      - deployments
      - replicasets
    verbs: ["list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - cronjobs
      - jobs
    verbs: ["list", "watch"]
  - apiGroups: ["autoscaling"]
    resources:
      - horizontalpodautoscalers
    verbs: ["list", "watch"]
  - apiGroups: ["policy"]
    resources:
      - poddisruptionbudgets
    verbs: ["list", "watch"]
  - apiGroups: ["certificates.k8s.io"]
    resources:
      - certificatesigningrequests
    verbs: ["list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - storageclasses
      - volumeattachments
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs: ["list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources:
      - networkpolicies
      - ingresses
    verbs: ["list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: kube-state-metrics
    namespace: castai-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  namespace: castai-agent
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - kwok
      containers:
        - name: kube-state-metrics
          image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.10.1
          ports:
            - containerPort: 8080
              name: http-metrics
            - containerPort: 8081
              name: telemetry
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: castai-agent
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
    - name: telemetry
      port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: kube-state-metrics
