// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/castai/cluster-controller/internal/k8s (interfaces: Client)

// Package mock_k8s is a generated GoMock package.
package mock_k8s

import (
	context "context"
	reflect "reflect"
	time "time"

	k8s "github.com/castai/cluster-controller/internal/k8s"
	gomock "github.com/golang/mock/gomock"
	logrus "github.com/sirupsen/logrus"
	v1 "k8s.io/api/core/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	kubernetes "k8s.io/client-go/kubernetes"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Clientset mocks base method.
func (m *MockClient) Clientset() kubernetes.Interface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clientset")
	ret0, _ := ret[0].(kubernetes.Interface)
	return ret0
}

// Clientset indicates an expected call of Clientset.
func (mr *MockClientMockRecorder) Clientset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clientset", reflect.TypeOf((*MockClient)(nil).Clientset))
}

// CordonNode mocks base method.
func (m *MockClient) CordonNode(arg0 context.Context, arg1 *v1.Node) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CordonNode", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CordonNode indicates an expected call of CordonNode.
func (mr *MockClientMockRecorder) CordonNode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CordonNode", reflect.TypeOf((*MockClient)(nil).CordonNode), arg0, arg1)
}

// DeletePod mocks base method.
func (m *MockClient) DeletePod(arg0 context.Context, arg1 v10.DeleteOptions, arg2 v1.Pod, arg3 int, arg4 time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePod", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePod indicates an expected call of DeletePod.
func (mr *MockClientMockRecorder) DeletePod(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePod", reflect.TypeOf((*MockClient)(nil).DeletePod), arg0, arg1, arg2, arg3, arg4)
}

// EvictPod mocks base method.
func (m *MockClient) EvictPod(arg0 context.Context, arg1 v1.Pod, arg2 time.Duration, arg3 schema.GroupVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EvictPod", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// EvictPod indicates an expected call of EvictPod.
func (mr *MockClientMockRecorder) EvictPod(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EvictPod", reflect.TypeOf((*MockClient)(nil).EvictPod), arg0, arg1, arg2, arg3)
}

// ExecuteBatchPodActions mocks base method.
func (m *MockClient) ExecuteBatchPodActions(arg0 context.Context, arg1 []*v1.Pod, arg2 func(context.Context, v1.Pod) error, arg3 string) ([]*v1.Pod, []k8s.PodActionFailure) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteBatchPodActions", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*v1.Pod)
	ret1, _ := ret[1].([]k8s.PodActionFailure)
	return ret0, ret1
}

// ExecuteBatchPodActions indicates an expected call of ExecuteBatchPodActions.
func (mr *MockClientMockRecorder) ExecuteBatchPodActions(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteBatchPodActions", reflect.TypeOf((*MockClient)(nil).ExecuteBatchPodActions), arg0, arg1, arg2, arg3)
}

// GetNodeByIDs mocks base method.
func (m *MockClient) GetNodeByIDs(arg0 context.Context, arg1, arg2, arg3 string) (*v1.Node, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNodeByIDs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*v1.Node)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNodeByIDs indicates an expected call of GetNodeByIDs.
func (mr *MockClientMockRecorder) GetNodeByIDs(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNodeByIDs", reflect.TypeOf((*MockClient)(nil).GetNodeByIDs), arg0, arg1, arg2, arg3)
}

// Log mocks base method.
func (m *MockClient) Log() logrus.FieldLogger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Log")
	ret0, _ := ret[0].(logrus.FieldLogger)
	return ret0
}

// Log indicates an expected call of Log.
func (mr *MockClientMockRecorder) Log() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockClient)(nil).Log))
}

// PatchNode mocks base method.
func (m *MockClient) PatchNode(arg0 context.Context, arg1 *v1.Node, arg2 func(*v1.Node)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchNode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchNode indicates an expected call of PatchNode.
func (mr *MockClientMockRecorder) PatchNode(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchNode", reflect.TypeOf((*MockClient)(nil).PatchNode), arg0, arg1, arg2)
}

// PatchNodeStatus mocks base method.
func (m *MockClient) PatchNodeStatus(arg0 context.Context, arg1 string, arg2 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchNodeStatus", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PatchNodeStatus indicates an expected call of PatchNodeStatus.
func (mr *MockClientMockRecorder) PatchNodeStatus(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchNodeStatus", reflect.TypeOf((*MockClient)(nil).PatchNodeStatus), arg0, arg1, arg2)
}
