// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proxy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterTunnel_Connect_FullMethodName = "/clustertunnel.v1alpha1.ClusterTunnel/Connect"
)

// ClusterTunnelClient is the client API for ClusterTunnel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterTunnelClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelMessage, TunnelMessage], error)
}

type clusterTunnelClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterTunnelClient(cc grpc.ClientConnInterface) ClusterTunnelClient {
	return &clusterTunnelClient{cc}
}

func (c *clusterTunnelClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelMessage, TunnelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterTunnel_ServiceDesc.Streams[0], ClusterTunnel_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelMessage, TunnelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterTunnel_ConnectClient = grpc.BidiStreamingClient[TunnelMessage, TunnelMessage]

// ClusterTunnelServer is the server API for ClusterTunnel service.
// All implementations must embed UnimplementedClusterTunnelServer
// for forward compatibility.
type ClusterTunnelServer interface {
	Connect(grpc.BidiStreamingServer[TunnelMessage, TunnelMessage]) error
	mustEmbedUnimplementedClusterTunnelServer()
}

// UnimplementedClusterTunnelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterTunnelServer struct{}

func (UnimplementedClusterTunnelServer) Connect(grpc.BidiStreamingServer[TunnelMessage, TunnelMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedClusterTunnelServer) mustEmbedUnimplementedClusterTunnelServer() {}
func (UnimplementedClusterTunnelServer) testEmbeddedByValue()                       {}

// UnsafeClusterTunnelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterTunnelServer will
// result in compilation errors.
type UnsafeClusterTunnelServer interface {
	mustEmbedUnimplementedClusterTunnelServer()
}

func RegisterClusterTunnelServer(s grpc.ServiceRegistrar, srv ClusterTunnelServer) {
	// If the following call pancis, it indicates UnimplementedClusterTunnelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterTunnel_ServiceDesc, srv)
}

func _ClusterTunnel_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterTunnelServer).Connect(&grpc.GenericServerStream[TunnelMessage, TunnelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterTunnel_ConnectServer = grpc.BidiStreamingServer[TunnelMessage, TunnelMessage]

// ClusterTunnel_ServiceDesc is the grpc.ServiceDesc for ClusterTunnel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterTunnel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clustertunnel.v1alpha1.ClusterTunnel",
	HandlerType: (*ClusterTunnelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _ClusterTunnel_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proxy.proto",
}
