// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TunnelMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TunnelMessage_HttpRequest
	//	*TunnelMessage_HttpResponseStart
	//	*TunnelMessage_HttpResponseBody
	//	*TunnelMessage_HttpResponseEnd
	//	*TunnelMessage_Heartbeat
	Payload       isTunnelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelMessage) GetPayload() isTunnelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelMessage) GetHttpRequest() *HttpRequest {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_HttpRequest); ok {
			return x.HttpRequest
		}
	}
	return nil
}

func (x *TunnelMessage) GetHttpResponseStart() *HttpResponseStart {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_HttpResponseStart); ok {
			return x.HttpResponseStart
		}
	}
	return nil
}

func (x *TunnelMessage) GetHttpResponseBody() *HttpResponseBody {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_HttpResponseBody); ok {
			return x.HttpResponseBody
		}
	}
	return nil
}

func (x *TunnelMessage) GetHttpResponseEnd() *HttpResponseEnd {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_HttpResponseEnd); ok {
			return x.HttpResponseEnd
		}
	}
	return nil
}

func (x *TunnelMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isTunnelMessage_Payload interface {
	isTunnelMessage_Payload()
}

type TunnelMessage_HttpRequest struct {
	HttpRequest *HttpRequest `protobuf:"bytes,1,opt,name=http_request,json=httpRequest,proto3,oneof"`
}

type TunnelMessage_HttpResponseStart struct {
	HttpResponseStart *HttpResponseStart `protobuf:"bytes,4,opt,name=http_response_start,json=httpResponseStart,proto3,oneof"`
}

type TunnelMessage_HttpResponseBody struct {
	HttpResponseBody *HttpResponseBody `protobuf:"bytes,5,opt,name=http_response_body,json=httpResponseBody,proto3,oneof"`
}

type TunnelMessage_HttpResponseEnd struct {
	HttpResponseEnd *HttpResponseEnd `protobuf:"bytes,6,opt,name=http_response_end,json=httpResponseEnd,proto3,oneof"`
}

type TunnelMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

func (*TunnelMessage_HttpRequest) isTunnelMessage_Payload() {}

func (*TunnelMessage_HttpResponseStart) isTunnelMessage_Payload() {}

func (*TunnelMessage_HttpResponseBody) isTunnelMessage_Payload() {}

func (*TunnelMessage_HttpResponseEnd) isTunnelMessage_Payload() {}

func (*TunnelMessage_Heartbeat) isTunnelMessage_Payload() {}

type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers       []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *HttpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HttpResponseStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponseStart) Reset() {
	*x = HttpResponseStart{}
	mi := &file_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponseStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponseStart) ProtoMessage() {}

func (x *HttpResponseStart) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponseStart.ProtoReflect.Descriptor instead.
func (*HttpResponseStart) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *HttpResponseStart) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponseStart) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponseStart) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HttpResponseBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponseBody) Reset() {
	*x = HttpResponseBody{}
	mi := &file_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponseBody) ProtoMessage() {}

func (x *HttpResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponseBody.ProtoReflect.Descriptor instead.
func (*HttpResponseBody) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *HttpResponseBody) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponseBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type HttpResponseEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponseEnd) Reset() {
	*x = HttpResponseEnd{}
	mi := &file_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponseEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponseEnd) ProtoMessage() {}

func (x *HttpResponseEnd) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponseEnd.ProtoReflect.Descriptor instead.
func (*HttpResponseEnd) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *HttpResponseEnd) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampMs   int64                  `protobuf:"varint,1,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\x16clustertunnel.v1alpha1\"\xb5\x03\n" +
	"\rTunnelMessage\x12H\n" +
	"\fhttp_request\x18\x01 \x01(\v2#.clustertunnel.v1alpha1.HttpRequestH\x00R\vhttpRequest\x12[\n" +
	"\x13http_response_start\x18\x04 \x01(\v2).clustertunnel.v1alpha1.HttpResponseStartH\x00R\x11httpResponseStart\x12X\n" +
	"\x12http_response_body\x18\x05 \x01(\v2(.clustertunnel.v1alpha1.HttpResponseBodyH\x00R\x10httpResponseBody\x12U\n" +
	"\x11http_response_end\x18\x06 \x01(\v2'.clustertunnel.v1alpha1.HttpResponseEndH\x00R\x0fhttpResponseEnd\x12A\n" +
	"\theartbeat\x18\x03 \x01(\v2!.clustertunnel.v1alpha1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xa6\x01\n" +
	"\vHttpRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x128\n" +
	"\aheaders\x18\x04 \x03(\v2\x1e.clustertunnel.v1alpha1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\"\x8d\x01\n" +
	"\x11HttpResponseStart\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x128\n" +
	"\aheaders\x18\x03 \x03(\v2\x1e.clustertunnel.v1alpha1.HeaderR\aheaders\"E\n" +
	"\x10HttpResponseBody\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"0\n" +
	"\x0fHttpResponseEnd\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\".\n" +
	"\tHeartbeat\x12!\n" +
	"\ftimestamp_ms\x18\x01 \x01(\x03R\vtimestampMs\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2l\n" +
	"\rClusterTunnel\x12[\n" +
	"\aConnect\x12%.clustertunnel.v1alpha1.TunnelMessage\x1a%.clustertunnel.v1alpha1.TunnelMessage(\x010\x01B9Z7github.com/castai/cluster-controller/internal/tunnel/pbb\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proxy_proto_goTypes = []any{
	(*TunnelMessage)(nil),     // 0: clustertunnel.v1alpha1.TunnelMessage
	(*HttpRequest)(nil),       // 1: clustertunnel.v1alpha1.HttpRequest
	(*HttpResponseStart)(nil), // 2: clustertunnel.v1alpha1.HttpResponseStart
	(*HttpResponseBody)(nil),  // 3: clustertunnel.v1alpha1.HttpResponseBody
	(*HttpResponseEnd)(nil),   // 4: clustertunnel.v1alpha1.HttpResponseEnd
	(*Heartbeat)(nil),         // 5: clustertunnel.v1alpha1.Heartbeat
	(*Header)(nil),            // 6: clustertunnel.v1alpha1.Header
}
var file_proxy_proto_depIdxs = []int32{
	1, // 0: clustertunnel.v1alpha1.TunnelMessage.http_request:type_name -> clustertunnel.v1alpha1.HttpRequest
	2, // 1: clustertunnel.v1alpha1.TunnelMessage.http_response_start:type_name -> clustertunnel.v1alpha1.HttpResponseStart
	3, // 2: clustertunnel.v1alpha1.TunnelMessage.http_response_body:type_name -> clustertunnel.v1alpha1.HttpResponseBody
	4, // 3: clustertunnel.v1alpha1.TunnelMessage.http_response_end:type_name -> clustertunnel.v1alpha1.HttpResponseEnd
	5, // 4: clustertunnel.v1alpha1.TunnelMessage.heartbeat:type_name -> clustertunnel.v1alpha1.Heartbeat
	6, // 5: clustertunnel.v1alpha1.HttpRequest.headers:type_name -> clustertunnel.v1alpha1.Header
	6, // 6: clustertunnel.v1alpha1.HttpResponseStart.headers:type_name -> clustertunnel.v1alpha1.Header
	0, // 7: clustertunnel.v1alpha1.ClusterTunnel.Connect:input_type -> clustertunnel.v1alpha1.TunnelMessage
	0, // 8: clustertunnel.v1alpha1.ClusterTunnel.Connect:output_type -> clustertunnel.v1alpha1.TunnelMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	file_proxy_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelMessage_HttpRequest)(nil),
		(*TunnelMessage_HttpResponseStart)(nil),
		(*TunnelMessage_HttpResponseBody)(nil),
		(*TunnelMessage_HttpResponseEnd)(nil),
		(*TunnelMessage_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
