// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/castai/cluster-controller/internal/nodes (interfaces: Drainer)

// Package mock_nodes is a generated GoMock package.
package mock_nodes

import (
	context "context"
	reflect "reflect"

	nodes "github.com/castai/cluster-controller/internal/nodes"
	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/api/core/v1"
)

// MockDrainer is a mock of Drainer interface.
type MockDrainer struct {
	ctrl     *gomock.Controller
	recorder *MockDrainerMockRecorder
}

// MockDrainerMockRecorder is the mock recorder for MockDrainer.
type MockDrainerMockRecorder struct {
	mock *MockDrainer
}

// NewMockDrainer creates a new mock instance.
func NewMockDrainer(ctrl *gomock.Controller) *MockDrainer {
	mock := &MockDrainer{ctrl: ctrl}
	mock.recorder = &MockDrainerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDrainer) EXPECT() *MockDrainerMockRecorder {
	return m.recorder
}

// Drain mocks base method.
func (m *MockDrainer) Drain(arg0 context.Context, arg1 nodes.DrainRequest) ([]*v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drain", arg0, arg1)
	ret0, _ := ret[0].([]*v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Drain indicates an expected call of Drain.
func (mr *MockDrainerMockRecorder) Drain(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drain", reflect.TypeOf((*MockDrainer)(nil).Drain), arg0, arg1)
}

// Evict mocks base method.
func (m *MockDrainer) Evict(arg0 context.Context, arg1 nodes.EvictRequest) ([]*v1.Pod, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evict", arg0, arg1)
	ret0, _ := ret[0].([]*v1.Pod)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evict indicates an expected call of Evict.
func (mr *MockDrainerMockRecorder) Evict(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evict", reflect.TypeOf((*MockDrainer)(nil).Evict), arg0, arg1)
}
