name: E2E tests

concurrency:
  group: e2e-tests

on:
  workflow_call:
    inputs:
      image-repository:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    secrets:
      CASTAI_API_TOKEN:
        required: true
      GCP_CREDENTIALS:
        required: true

jobs:
  e2e-tests:
    name: Run e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - uses: azure/setup-kubectl@v4
      - uses: azure/setup-helm@v4.2.0

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
          install_components: 'gke-gcloud-auth-plugin'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Run e2e tests
        env:
          CLUSTER_CONTROLLER_IMAGE_REPOSITORY: ${{ inputs.image-repository }}
          CLUSTER_CONTROLLER_IMAGE_TAG: ${{ inputs.image-tag }}
          CLUSTER_NAME: e2e-cluster-controller
          CLUSTER_REGION: us-central1
          CASTAI_API_TOKEN: ${{ secrets.CASTAI_API_TOKEN }}
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          go test -timeout 30m -parallel=10 ./e2e

