name: FOSSA

on:
  push:
    branches:
      - main
    schedule:
      - cron: "0 */6 * * *"
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
