name: Main build

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    name: Build
    outputs:
      image-tag: ${{ env.VERSION_TAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.5'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-build-

      - name: Get release tag
        if: github.event_name == 'release'
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Get version
        run: echo "VERSION_TAG=$(git describe --tags)" >> $GITHUB_ENV

      - name: Build Go binary amd64
        run: go build -ldflags "-s -w -X main.GitCommit=$GITHUB_SHA -X main.GitRef=$GITHUB_REF -X main.Version=${RELEASE_TAG:-$VERSION_TAG}" -o bin/castai-cluster-controller-amd64 .
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0

      - name: Build Go binary arm64
        run: go build -ldflags "-s -w -X main.GitCommit=$GITHUB_SHA -X main.GitRef=$GITHUB_REF -X main.Version=${RELEASE_TAG:-$VERSION_TAG}" -o bin/castai-cluster-controller-arm64 .
        env:
          GOOS: linux
          GOARCH: arm64
          CGO_ENABLED: 0

      - name: Test
        run: go test -short -race ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_BUILDER_JSON_KEY }}

      - name: Build and push main
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: us-docker.pkg.dev/castai-hub/library/cluster-controller:${{ env.VERSION_TAG }}

      - name: Build and push release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/arm64,linux/amd64
          tags: |
            us-docker.pkg.dev/castai-hub/library/cluster-controller:${{ env.RELEASE_TAG }}
            us-docker.pkg.dev/castai-hub/library/cluster-controller:latest

      - name: Docker pull for fossa main
        if: github.event_name == 'release'
        run: docker pull us-docker.pkg.dev/castai-hub/library/cluster-controller:${{ env.RELEASE_TAG }}

      - name: FOSSA scan docker image
        if: github.event_name == 'release'
        continue-on-error: true
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          container: us-docker.pkg.dev/castai-hub/library/cluster-controller:${{ env.RELEASE_TAG }}

  e2e-tests:
    needs: [build]
    uses: ./.github/workflows/e2e.yaml
    with:
      image-repository: us-docker.pkg.dev/castai-hub/library/cluster-controller
      image-tag: ${{ needs.build.outputs.image-tag }}
    secrets:
      CASTAI_API_TOKEN: ${{ secrets.CASTAI_API_TOKEN }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
